import type { Drawing } from '../library.ts'
import { cassette } from './cassette.ts'

/**
 * Every imported drawing, generated by `npm run import`.
 *
 * Do not edit by hand — it is rewritten from the contents of this folder on
 * every import. To remove a drawing, delete its file and re-run the importer
 * (or any import) to refresh this list.
 */
export const IMPORTED: Drawing[] = [
  cassette,
]
